### ISSUE TITLE
[Bug]: No scroll on station column for chat window

### ISSUE THREAD

**Issue by frspin** [DJ2LS/FreeDATA#790]
### FreeDATA Version

0.16.2alpha

### What operating system are you using?

Ubuntu

### Operating System Version

24.04 full updated

### Architecture

x86

### Area of problem

GUI

### Describe the bug

When number of station in chat overcome  column height no scroll appear and latest stations are unreachable

### To Reproduce

Save  station in chat area more than number required to fill column area

### Expected behavior

A scroll bar for reaching latest station as in conversation area

**Comment by DJ2LS** [comment]
Interesting, this should work as I tested this yesterday. Will have a look on this again. Thanks for reporting Von meinem iPhone gesendetAm 26.08.2024 um 11:21 schrieb frspin ***@***.***>:﻿
FreeDATA Version
0.16.2alpha
What operating system are you using?
Ubuntu
Operating System Version
24.04 full updated
Architecture
x86
Area of problem
GUI
Describe the bug
When number of station in chat overcome  column height no scroll appear and latest stations are unreachable
To Reproduce
Save  station in chat area more than number required to fill column area
Expected behavior
A scroll bar for reaching latest station as in conversation area
Screenshots
No response
Log Files
No response
Additional context
No response

**Comment by DJ2LS** [comment]
@frspin I can't reproduce this issue. Did you run a git pull and a npm run build as well? Which browser are you using?

**Comment by frspin** [comment]
Il 27/08/24 12:00, DJ2LS ha scritto:
> @frspin <https://github.com/frspin> I can't reproduce this issue. Did 
> you run a git pull and a npm run build as well? Which browser are you using?


"Git pull" from develop branch was done but not "npm run build"

Now done also this step and waiting for a new station in chat area for 
testing.
Where is documented "npm run build step?"

Franco Spinelli
IW2DHW

**Comment by frspin** [comment]
Il 28/08/24 14:50, DJ2LS ha scritto:
> the npm run build step isnt documented, yet. I opened an issue for 
> rewriting of develpment installation instructions.
> 
> So, is this issue still valid? If its fixed, please close the issue.

Unable to tell.
I am waiting a new station with a chat message for testing it.

How can I "add" a new station to chat?
Also manipulating by and Sqlite database.

Franco Spinelli
IW2DHW

**Comment by frspin** [comment]
Finally get a new station and now scroll is working.

So this bug is solved and issue can be closed
